### ISSUE TITLE
Prefetching blocked when route has `data`

### ISSUE THREAD

**Issue by rolaveric** [mgechev/ngx-quicklink#10]
The blacklist handling in `QuicklinkStrategy` by checking for a `route.data.preload` value with a simple falsy check:
https://github.com/mgechev/ngx-quicklink/blob/master/src/quicklink-strategy.service.ts#L17
Trouble is this means that any route with `data` is, by default, blacklisted.

Simplest solution would be to change `!route.data.preload` to `route.data.preload === false`.

**Comment by mgechev** [comment]
Oh, good catch. Would you open a PR?

**Comment by rolaveric** [comment]
Will do, I'll open one tonight from home.
