### ISSUE TITLE
Routes can potentially be preloaded multiple times

### ISSUE THREAD

**Issue by rolaveric** [mgechev/ngx-quicklink#11]
I've run into a scenario where the IntersectionObserver fires multiple times, causing `QuicklinkStrategy.preload()` to be called multiple times for the same routes, which then causes those modules to be constructed multiple times.
In most cases this is pretty benign, but I've got a scenario where I'm handling NgUpgrade work as part of the module constructor, and it's causing errors from trying to load AngularJS multiple times.

The simplest solution I think is to track which modules have already passed the tests for preloading (specifically their `loadChildren` string) and short circuit if they've already being handled.

Though maybe there's an argument that this should be handled by the Angular Router, where `load()` does the work once for the same route.

**Comment by mgechev** [comment]
>The simplest solution I think is to track which modules have already passed the tests for preloading (specifically their `loadChildren` string) and short circuit if they've already being handled.

This sounds good. My concern would be for relative paths. There could be multiple routes with the same value of `loadChildren`. Maybe we can even store the `Route` object in a `Set` and this could be fine. Of each `Route` we have a single instance in the entire application.
