### ISSUE TITLE
Error: NG0203: inject() must be called from an injection context such as a constructor

### ISSUE THREAD

**Issue by jack1ripper** [mgechev/ngx-quicklink#135]
I'm working with angular universal to handle ssr along with lazy loading module.
angular version: 14.0.0
ngx-quiclink: 0.3.0

when added 
` preloadingStrategy: QuicklinkStrategy`
to my app.module the error blow appears, and my app is shut down.

Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203

**Comment by mgechev** [comment]
Can't reproduce with latest version. Feel free to reopen if this issue persists.
