### ISSUE TITLE
Describe the way it should be used with standalone components

### ISSUE THREAD

**Issue by th0r** [mgechev/ngx-quicklink#137]
Is it correct that in case of standalone components `QuicklinkModule` must be imported into every such component?
Thanks!

**Comment by mgechev** [comment]
Yes, would you want to contribute with the docs?

**Comment by th0r** [comment]
Well, it's not very convenient. Maybe there is some other way?

**Comment by mgechev** [comment]
That's how standalone components work. Just the way you'd need to import `FormsModule` to use `[(ngModel)]` you need `QuicklinkModule` for the corresponding directive.
