### ISSUE TITLE
Nested Lazy Loaded - Not being loaded

### ISSUE THREAD

**Issue by vivekdoshi2** [mgechev/ngx-quicklink#14]
I do have folder structure like this : 

```
App
    First
        First Child

    Second
```
All components are lazy loaded ,

I have put the links of first and second components on the `app.component.ts` , and its loading it perfectly ,

And then I have put the link of FirstChild inside the `first.component.ts` and also into the `app.component.ts` , 

**Expected behaviour :**

First it should load the First and Second component as its in the view port from app.component ,
then when you click on First , it loading the First component with link of FirstChild component , so it should also get load as it also now in the view port

But FirstChild component never gets load , until you click upon that.

I have also created a shared module as suggested : https://github.com/mgechev/angular-realworld-example-app-qucklink/commit/33ea101c7d84bb5ca086f107148bbc958659f83f

Link to code : https://github.com/vivekdoshi2/quicklink-nested-lazyloaded

**Comment by mgechev** [comment]
@vivekdoshi2 thanks for reporting the issue! Should be fixed [here](https://github.com/mgechev/ngx-quicklink/commit/63856451cf1a9056a3527cc8bbe511e5302c6f82#diff-1ddef80121254423239faeee35d9507aR46).

Try upgrading to 0.0.9.

**Comment by vivekdoshi2** [comment]
@mgechev ,

Working now , thanks for the great update.
