### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by th0r** [mgechev/ngx-quicklink#142]
I've opened [an issue to support Angular 15](https://github.com/mgechev/ngx-quicklink/issues/140) a month ago and none of the maintainers commented there yet.

@mgechev do you plan to support this project in the future? If not then maybe you could recommend some analog?

Thank you for your work!

**Comment by RodolfoXDR** [comment]
I would also like to know any other alternative in case this project is abandoned

**Comment by L-X-T** [comment]
I'm also interested in this and I'm going to contact @mgechev on Twitter regarding this.

**Comment by mgechev** [comment]
I'll publish an update sometime today/tomorrow. Sorry for the delay, missed this notification.

**Comment by mgechev** [comment]
Just published v0.3.1.
