### ISSUE TITLE
Missing support for standalone components

### ISSUE THREAD

**Issue by L-X-T** [mgechev/ngx-quicklink#147]
Hi @mgechev,

thanks for updating the package's peerDependencies to reflect support for NG 15.

I think it's still not support routes using standalone components with the loadComponent import. So I my example app I would have expected it to work with the new loadComponent method as well, but it just loads the modules with loadChildren (NgModule) import.

All the best
Alex T.

**Comment by mgechev** [comment]
There's support for standalone components. Check the example directory. Even in older versions the directive should work.
