### ISSUE TITLE
typo: perfetching

### ISSUE THREAD

**Issue by JohannesHoppe** [mgechev/ngx-quicklink#15]
Description of this repo:
>Quicklink perfetching strategy for the Angular router

Should be:
> Quicklink prefetching strategy for the Angular router

**Comment by mgechev** [comment]
Thanks for pointing this out! Would you open a PR if you have a minute?

**Comment by JohannesHoppe** [comment]
I would, but I can't send a PR for the description of a GH repo! 😉 

<img width="602" alt="Screen Shot 2019-03-13 at 00 51 27" src="https://user-images.githubusercontent.com/640639/54243844-5a73eb00-452a-11e9-851d-5a33e131a2c9.png">

**Comment by mgechev** [comment]
Fixed! Thanks for the catch :)
