### ISSUE TITLE
Not prefetching on Async loaded data

### ISSUE THREAD

**Issue by Taylorsuk** [mgechev/ngx-quicklink#16]
Prefetching is working fine on a static link within the viewport:

**e.g**: `<a routerLink="/account-subscription" role="button">Subscription</a>`

Prefetch does not work when the anchor is rendered in the template asynchronously:

**e.g.**:

component.ts
```
  get subHeaderLinks(): Observable<IHeaderLink[]> {
    return this.linkService.currentSubheaderLinks;
  }
```

component.html
```
<li *ngFor="let link of (subHeaderLinks | async)">
  <a routerLink="/{{link.routerLink}}" routerLinkActive="active-link">{{link.linkTitle}}</a>
</li>
```

**Comment by mgechev** [comment]
You can find the fix [here](https://github.com/mgechev/ngx-quicklink/commit/55200fe255208c2ef726b3a265a8b9529b26ec35).

Try 0.0.10.

**Comment by Taylorsuk** [comment]
Perfect, thanks 👍
