### ISSUE TITLE
Ignores routes with params

### ISSUE THREAD

**Issue by Taylorsuk** [mgechev/ngx-quicklink#17]
A path such as the below example does not prefetch. 

```
  {
    path: 'program-results/:id/:client',
    canActivate: [AuthGuard],
    loadChildren: 'pages/program-results/program-results.module#ProgramResultsModule'
  }
```

Testing this lazy route (`path: program-results`) works fine if no route params are used. 

Happy to put in some work and PR if you point me in the right direction, but i'm not very experienced. 

**EDIT**
I note this is on the TODO list, I'll wait direction 😃 : 

**quicklink-strategy.service.ts**
```
    const fullPath = findPath(this.router.config, route);
    // TODO(mgechev): make sure it works for parameterized routes
    if (this.queue.shouldPrefetch(fullPath)) {
      this.loading.add(route);
      return load();
    }
```

**Comment by mgechev** [comment]
Should be fine now :)

**Comment by mgechev** [comment]
That's the fix https://github.com/mgechev/ngx-quicklink/commit/b7f9eaa2f0188ecffd9b9f4aaee454b6e0cb2036#diff-e9e569eb08bea4efb64135a395857141R77

**Comment by Taylorsuk** [comment]
Yep, works perfectly! Thanks
