### ISSUE TITLE
Integrate QuickLink module to Lazy Loaded Module

### ISSUE THREAD

**Issue by sureshdotariya** [mgechev/ngx-quicklink#18]
I tried integrating quicklink module into App Module. It's not working for me. My Application has login Page  After user login, we will be taken to Dashboard Page (its lazy loaded module). I tried importing & exporting the 'QuickLink' module in ' Shared' module. This shared module is imported in Dashboard Module.

**App Module:**

`imports: [AppRoutingModule, QuicklinkModule]`

**App Routing Module:**
```
@NgModule({
  imports: [RouterModule.forRoot(app_routes, { preloadingStrategy: QuicklinkStrategy })],
  exports: [RouterModule]
}) 
```

**Shared Module:**

```
imports: [QuicklinkModule],
exports:[QuicklinkModule]
```

It's not working. I checked in chrome network tab. Side Menu URL's in Routerlink are not lazy loaded.

ngx-quicklink: 0.0.11
Angular CLI: 7.3.8
Node: 8.10.0
OS: darwin x64
Angular: 7.2.12
@angular-devkit/architect: 0.6.8
@angular-devkit/build-angular: 0.6.8
@angular-devkit/build-optimizer: 0.6.8
@angular-devkit/core: 0.6.8
@angular-devkit/schematics: 7.3.8
@angular/cli: 7.3.8
@ngtools/webpack : 6.0.8
@schematics/angular: 7.3.8
@schematics/update: 0.13.8
rxjs: 6.3.2
typescript:  3.1.3
webpack: 4.8.3

**Comment by mgechev** [comment]
For support requests, I'd recommend you to check StackOverflow and provide a minimal example. Thanks for giving ngx-quicklink a try 🙇
