### ISSUE TITLE
Error: Cannot find module '@angular/router/src/url_tree'

### ISSUE THREAD

**Issue by xmlking** [mgechev/ngx-quicklink#19]
When I was doing production builds, my docker build failed with this error:

looks like I  don't have   `@angular/router/src/` in my `node_modules`

```
ERROR in node_modules/ngx-quicklink/link.directive.d.ts(15,30): error TS2307: Cannot find module '@angular/router/src/url_tree'.
```

![image](https://user-images.githubusercontent.com/627951/55755767-d3207700-5a04-11e9-802d-6e1f92c8b645.png)

**Comment by xmlking** [comment]
looks like there is a breaking change in angular `8.0.0-beta.11`  for `@angular/router` , `src` is no more distributed .

**Comment by mgechev** [comment]
This should be fine now.

**Comment by jirungaray** [comment]
Still having this issue:
Angular CLI: 8.0.2
Node: 12.4.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

**Comment by mgechev** [comment]
Make sure you update to ngx-quicklink version 0.1.0.

**Comment by jirungaray** [comment]
I was working off an old version, updating to 0.1.0 fixed it. Thanks.
