### ISSUE TITLE
QUESTION: preload strategy library

### ISSUE THREAD

**Issue by johnpapa** [mgechev/ngx-quicklink#22]
would you be interested in expanding this to be a library of preload strategies? we could add several that you and i have.

right now i just make them into snippets. but some are more complicated than a single snippet

**Comment by mgechev** [comment]
I thought about this for a while. It makes sense for a lot of the strategies. In the same time I see Guess.js (not implemented as a preloading strategy) and ngx-quicklink as few examples of more complicated implementations.

Managing preloading strategies on one place would simplify maintenance, in the same time we should be very careful with code reuse across them to not break tree-shaking. You're right that most of them are quite small and fit really well into a snippet, others not. My concern would be to not bloat users' bundles with redundant code they don't use.

What do you think?

**Comment by johnpapa** [comment]
Good points. Another idea is to have a set of these strategies where they are separately installable. Could be one library with separate modules like material. Or separate libraries entirely. 

Another thing to consider is that many of these strategies could be intermixed. Or tweaked. So this is what also makes me think a guidance doc or snippets is best instead. 

In the end I really feel that having a resource for strategies is a good thing. If that is loose like guidance or more strict like a library —- I don’t think the exciting  matters as much as having one place to share some of the best guidance.

**Comment by mgechev** [comment]
I really like your posts on the topic. Do you think we can point to either your post or another document which organizes the strategies as a reference?

**Comment by mgechev** [comment]
Closing for now. Let me know if you have any comments :)
