### ISSUE TITLE
Bug: Ivy support

### ISSUE THREAD

**Issue by C1E1S1T** [mgechev/ngx-quicklink#23]
# 🐞 bug report

### Affected Package

 The issue is caused by package ngx-quicklink

### Description
Ivy support. 

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

ERROR in There is no typings path for LinkDirective in C:/Users/Dell/Documents/Proyectos tecnologicos/Arsus-Enterprise/node_modules/ngx-quicklink/link.directive.js.
We need to add an export for this class to a .d.ts typings file because Angular compiler needs to be able to reference this class in compiled code, such as templates.
The simplest fix for this is to ensure that this class is exported from the package's entry-point.

</code></pre>

## 🌍  Your Environment

**package.json:**
<pre><code>
    "@angular/animations": "^8.1.1",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.1.1",
    "@angular/core": "^8.1.1",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "^8.1.1",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "^8.1.1",
    "@angular/platform-browser-dynamic": "^8.1.1",
    "@angular/pwa": "^0.800.2",
    "@angular/router": "^8.1.1",
    "@angular/service-worker": "^8.1.1",
    "@capacitor/core": "1.1.0",
    "@ionic/angular": "^4.6.2",
    "@ngx-loading-bar/core": "^4.2.0",
    "@ngx-loading-bar/router": "^4.2.0",
    "@ngxs/logger-plugin": "^3.3.2",
    "@ngxs/store": "^3.3.2",
    "angulartics2": "^7.5.2",
    "echarts": "^4.2.1",
    "firebase": "^6.1.1",
    "hammerjs": "^2.0.8",
    "immutable": "^4.0.0-rc.12",
    "ngx-echarts": "^4.1.1",
    "ngx-stars": "^1.3.0",
    "rxjs": "6.5.2",
    "zone.js": "~0.9.1",
    "ngx-quicklink": "^0.1.0"

</code></pre>

**Anything else relevant?**

**Comment by mgechev** [comment]
Would you share a repo where I can reproduce the issue? I'll look at it early this week.

**Comment by mgechev** [comment]
Closing it due to inactivity. Feel free to open a new issue if this still persists. Would be great if you can share a repro as well.

**Comment by davidloiret** [comment]
I'm also able to reproduce this issue by updating to "@angular/...":"8.1.1" and by using remote "ngx-quicklink": "0.1.0".
Here the fork with the broken version https://github.com/davidloiret/ngx-quicklink/tree/master/example

**Comment by LanderBeeuwsaert** [comment]
Hello, just to drop in to say I have this issue as well.
I'm on Angular 8.1.2, and trying to enable IVY.
Seems that the compilation fails on this.

**Comment by mgechev** [comment]
Would you give a try the latest version 0.1.2.

**Comment by davidloiret** [comment]
Using version 0.1.2 it's working fine, thank you.

**Comment by Mohammad-Quanit** [comment]
@mgechev I am still facing this issue while `ng build` with enable ivy.
here's my package.json.
` "dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ngrx/effects": "^8.1.0",
    "@ngrx/entity": "^8.1.0",
    "@ngrx/router-store": "^8.1.0",
    "@ngrx/store": "^8.1.0",
    "@ngrx/store-devtools": "^8.1.0",
    "ngx-quicklink": "^0.1.0",
    "quicklink": "^1.0.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }`

**Comment by mgechev** [comment]
Explicitly set `ngx-quicklink` to version 0.1.5 and it'll work:

`"ngx-quicklink": "^0.1.0"` -> `"ngx-quicklink": "^0.1.5"`

Also, you don't need `quicklink` as a dependency.
