### ISSUE TITLE
 Unexpected value 'QuicklinkModule in quicklink.d.ts

### ISSUE THREAD

**Issue by fatalcaron** [mgechev/ngx-quicklink#24]
When building my app in AOT: 
 
ERROR in Unexpected value 'QuicklinkModule in .../node_modules/ngx-quicklink/ngx-quicklink.d.ts' imported by the module 'SharedModule in .../node_modules/ngx-quicklink/ngx-quicklink.d.ts' imported by the module 'SharedModule in .../src/app/shared/shared.module.ts'. Please add a @NgModule annotation.

Angular: 8.2.0
ngx-quicklink: 0.1.2

**Comment by mgechev** [comment]
Would you try `ngx-quicklink@0.1.3`. Sorry for the inconvenience.
