### ISSUE TITLE
ngx-quicklink works for simple links and seems to skip other

### ISSUE THREAD

**Issue by naveedahmed1** [mgechev/ngx-quicklink#26]
ngx-quicklink works for simple links but seems to skip links like the one below:

```
<mat-card class="mb25 pt0 pb0 pl0 pr0">
    <div fxLayout="row wrap" class="list-dashboard-actions">
        <div fxFlex fxFlex.xs="50">
            <a mat-ripple title="Post a Article" [routerLink]="['./atricles/new/']">
                <i class="material-icons">assignment</i>
                <div class="title">Post Article</div>
            </a>
        </div>
    </div>
</mat-card>
```

Here's the generated markup:

`<div fxflex="" fxflex.xs="50" style="flex: 1 1 0%; box-sizing: border-box;"><a class="mat-ripple" mat-ripple="" title="Post a New Article" href="https://www.mywebsite.com/atricles/new"><i class="material-icons">assignment</i><div class="title">Post Article</div></a></div>`

In my case these links are above the fold, but it still doesn't prefetch bundles for these links.

**Comment by mgechev** [comment]
Thanks for sharing your observations!

What do you mean by simple links? From the issue description, I'm not sure which links does `ngx-quicklink` skip.

Keep in mind that it'll prefetch **only** Angular router links, nothing else.

**Comment by naveedahmed1** [comment]
I mean it works for simple anchor tags, but it doesn't work for the link that is generated using above code, despite these are in view port. The bundles for these links are loaded when user click these links. Yes these are Angular router links.

**Comment by mgechev** [comment]
Would you share a minimal demo where I can reproduce the issue?

**Comment by naveedahmed1** [comment]
@mgechev ok I think I have solved this issue by making some changes to the routing details.

So, I can confirm it wasn't related to the markup.

But now I am having another issue, my app is behaving like if I have `preloadingStrategy `set to `PreloadAllModules`.

I have below url structure:

`/` (homepage)
`/account` (lazyloaded and has links pointing to section1, section2, section3)
`/account/section1` (lazyloaded and has links pointing to subsection1, subsection2, subsection3)
`/account/section2` (lazyloaded)
`/account/section3` (lazyloaded)

`/account/section1/subsection1` (lazyloaded)
`/account/section1/subsection2` (lazyloaded)
`/account/section1/subsection3` (lazyloaded)

Homepage i.e. url `/`  has a link pointing to `/account`.

When I open homepage i.e. `/` it prefetch all modules.

As per my understanding, it should prefetch module for just '/account'. And when user is at the '/account` url it should load bundles for section1, section2 and section3, similarly, when the user is at section 1 it should load bundles for subsection1,subsection2,subsection3.

**Comment by mgechev** [comment]
If in `/` you have link to a nested URL, ngx-quicklink will download the modules associated with each subpath.

For example, `/` with link to `/a/b/c/d` will download `/a`, `/a/b`, `/a/b/c/`, and `/a/b/c/d`.

Check if you don't point to any nested pages in the root.

Closing the issue for now, seems the description is no longer relevant.

**Comment by mgechev** [comment]
@naveedahmed1, side note, it's impressive to see you running `9.0.0-next.2`!

**Comment by mgechev** [comment]
@naveedahmed1 pinged you over email, we can keep the conversation there :)

**Comment by naveedahmed1** [comment]
Thank you @mgechev, I just replied your email :)
