### ISSUE TITLE
Prefetching doesn't work for lazy routes

### ISSUE THREAD

**Issue by th0r** [mgechev/ngx-quicklink#27]
Prefetching doesn't work for me when I load a lazy route with links to other lazy routes.

Here is my config:

```ts
@NgModule({
  imports: [SharedModule, AppRoutingModule]
})
export class AppModule {}

@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      onSameUrlNavigation: 'reload',
      relativeLinkResolution: 'corrected',
      preloadingStrategy: QuicklinkStrategy
    })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}

@NgModule({
  imports: [CommonModule, RouterModule, QuicklinkModule],
  exports: [CommonModule, RouterModule, QuicklinkModule]
})
export class SharedModule {}

@NgModule({
  imports: [
    SharedModule,
    RouterModule.forChild(lazyModuleRoutes)
  ]
})
export class LazyModule {}
```

I tried to debug the problem and it appeared that `PrefetchRegistry#shouldPrefetch` method is being called with proper urls but `this.trees` array is empty here:
https://github.com/mgechev/ngx-quicklink/blob/d7bd54c0c8b34822efee208b8631a39fc268d436/src/prefetch-registry.service.ts#L20-L23

I added a few console.logs after that: 

- Added `console.log("created a registry");` to the constructor of `PrefetchRegistry`:
https://github.com/mgechev/ngx-quicklink/blob/d7bd54c0c8b34822efee208b8631a39fc268d436/src/prefetch-registry.service.ts#L12-L14

- Added `console.log("added a tree", tree.toString(), 'this.trees.length =', this.trees.length);` to the `PrefetchRegistry#add` method:
https://github.com/mgechev/ngx-quicklink/blob/d7bd54c0c8b34822efee208b8631a39fc268d436/src/prefetch-registry.service.ts#L16-L18

And here are the results:
```
created a registry
created a registry
added a tree /path-to-lazy-route-on-screen this.trees.length = 1
should prefetch called for /path-to-lazy-route-on-screen this.trees.length = 0
```
Note that `PrefetchRegistry` was created twice and seems like `shouldPrefetch` method was called on the wrong instance with empty `trees` array.

**Comment by mgechev** [comment]
Hey @th0r, thanks for giving this a try! Before I dig into this, would you double check that you're following:

>Note that to make the module available in lazy-loaded modules as well you need to import it in a shared module and export it. Look at this commit to see how ngx-quicklink is integrated in the angular-realworld-example-app.

from the [readme](https://github.com/mgechev/ngx-quicklink#usage). Here's [a guide](https://web.dev/route-preloading-in-angular/#using-the-quicklink-preloading-strategy-across-multiple-lazy-loaded-modules) which explains this further.

**Comment by th0r** [comment]
Hey @mgechev, a simplifyed modules config that I use can be found in the main post. AFAIK it uses correct configuration of the SharedModule. Thanks for looking into it!

**Comment by th0r** [comment]
Hey @mgechev, were you able to take a look at it?

**Comment by mgechev** [comment]
You can try `ngx-quicklink@0.1.4`.

**Comment by th0r** [comment]
@mgechev it works now! Thanks a lot!
