### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by th0r** [mgechev/ngx-quicklink#28]
Seems like there is a memory leak in `PrefetchRegistry` service.

I added `console.log('global registry size =', this.trees.length)` here:
https://github.com/mgechev/ngx-quicklink/blob/d7bd54c0c8b34822efee208b8631a39fc268d436/src/prefetch-registry.service.ts#L16-L18

And during back and forth navigation from one lazy route to another (both of them contain visible `routerLink`s) logs show that global registry size just grows despite the fact that the links are the same.

Shouldn't `PrefetchRegistry#add` contain code that checks if a new tree is already in the registry?

And also shouldn't all the already prefetched trees be removed from this global registry?

Thanks!

**Comment by mgechev** [comment]
Yes, that's a known issue. There's a performance iteration that I'm planning for the next few weeks. I'll address a few issues there including this for now.

**Comment by th0r** [comment]
Great! Thanks!
