### ISSUE TITLE
Only Angular v8 support?

### ISSUE THREAD

**Issue by AsifulNobel** [mgechev/ngx-quicklink#29]
Does this library support Angular v8 only? If yes, is there a previous version that is compatible with Angular v7?

I was trying to use this on an existing project which uses Angular v7. But it does not seem to do any kind of preloading.

**Comment by mgechev** [comment]
`ngx-quicklink` works with Angular >=6. Maybe you've misconfigured the module?

**Comment by AsifulNobel** [comment]
It was my mistake and it is working correctly. So, I am closing this issue.
