### ISSUE TITLE
manual override  prefetch links behavior for certain links 

### ISSUE THREAD

**Issue by xmlking** [mgechev/ngx-quicklink#3]
it would be nice to have manual override prefetch behavior even the links are in viewport
e.g., I have `admin` and `user` links in landing page, but I don't want to prefetch `admin` links ... 
```
<a routerLink="/dashboard/grid/crud-table" prefetch=false>CRUD Table</a>
```

**Comment by mgechev** [comment]
@xmlking if you have a guard for the `admin` route `ngx-quicklink` would not prefetch the `admin` link.

This sounds like a good idea for sure, my only motivation for not introducing such feature would be to keep the library small.

**Comment by xmlking** [comment]
Agree on keeping it small. One issue I can imagine with my ask is, if we have  two+ anchor elements with same link, but diffrent `prefetch` values, it may misbehave.
May be the next best place to keep prefetch preference is, in router definition `{ data : { prefetch : true } }`

**Comment by mgechev** [comment]
@xmlking I'd go with blacklisting instead of whitelisting.

Few improvements I'm thinking about:

- Blacklisting of lazy-loaded modules
- Do not require intersection observers polyfill by downloading all the links on the page of not available

**Comment by xmlking** [comment]
Just F.Y.I... i made module to help lazy load media and trigger animations based in content in `viewport`

Src: https://github.com/xmlking/ngx-starter-kit/tree/develop/libs/ngx-utils

Demo : https://xmlking.github.io/ngx-starter-kit/dashboard/experiments/viewport  (username: sumo3, passowrd: demo)

**Comment by mgechev** [comment]
Good job!

**Comment by mgechev** [comment]
Introduced it as part of `ngx-quicklink@0.0.4`. You can specify the modules which you don't want to preload in `data: { preload: false }`.
