### ISSUE TITLE
Secondary routes support

### ISSUE THREAD

**Issue by krzysztof-grzybek** [mgechev/ngx-quicklink#31]
Hi!
I would like to have support for the [secondary routes](https://angular.io/guide/router#displaying-multiple-routes-in-named-outlets).
Currently, it doesn't work, it can be checked and tested [here](https://github.com/krzysztof-grzybek/angular-realworld-example-app-qucklink/commit/7c747436363c6515faefb68408abaf7e8da89903).

Do You plan to add support for this? Would You eventually review a PR if I will create one?

**Comment by mgechev** [comment]
Hey @krzysztof-grzybek yes, feel free to open a PR.
