### ISSUE TITLE
Angular 9 Ivy support

### ISSUE THREAD

**Issue by naturalfreak** [mgechev/ngx-quicklink#32]
Not loaded module when using angular 9, does it support?

**Comment by mgechev** [comment]
Angular version 9 is supported. Make sure you're using version 0.1.5 or above.

**Comment by BrayanVG** [comment]
Hello Minko, the same thing happens to me currently in Angular version 9.1.4, and the version of ngx-quicklink 0.2.1, I have everything well configured, the routerLink in the view, and it does not preload the module that I have

**Comment by Buu97** [comment]
Hi. I'm using Angular 10.0.4 and ngx-quicklink 0.2.7.
It does not seem to preload either.
Went to inspect the links and the attribute `ngx-ql` was set, yet no preloading.

**Comment by BrayanValdesG** [comment]
> Hi. I'm using Angular 10.0.4 and ngx-quicklink 0.2.7.
> It does not seem to preload either.
> Went to inspect the links and the attribute `ngx-ql` was set, yet no preloading.

I installed the package and it worked perfectly for me, uninstalled and reinstalled and whoala
