### ISSUE TITLE
LinkDirective provides incorrect typing for `routerLink` input, it mismatches to the one provided by Angular

### ISSUE THREAD

**Issue by Niaro** [mgechev/ngx-quicklink#41]
After turning the angular compilers option `strictTemplates` `routerLink` started throwing out a type error since for some reason the compiler picks up the type definition for quicklinks LinkDirective instead of the Angulars `RouterLinkWithHref`!

This is a matter of one minute!

**Comment by mgechev** [comment]
Thanks for pointing this out! Let me know if you'd want to take this issue.

**Comment by Niaro** [comment]
@mgechev here we are! #43

**Comment by mgechev** [comment]
It's out in 0.2.1.

**Comment by Niaro** [comment]
@mgechev Thank you very much!
