### ISSUE TITLE
Pre fetching doesn't work for Module involves Route paths with ID

### ISSUE THREAD

**Issue by askudhay** [mgechev/ngx-quicklink#48]
Thanks @mgechev for this wonderful package.. 

### Issue

It works great for routerLinks that don't involve Route path parameters..

If the routerLink is something like this `<a routerLink="pokemon+{{ i }}">Pokemon&nbsp;{{ i }} </a>`and the route configuration looks like below, then QuickLink doesnt work - I mean not preloading the PokemonStatsModule module..

For ex:

```
  {
    path: 'pokemon/:id',
    loadChildren: () =>
      import('./pokemon-stats/pokemon-stats.module').then(
        (m) => m.PokemonStatsModule
      ),
  }
```

Please let me know if I need to configure it differently to make QuickLink work.

Thanks again!

**Comment by jlilly** [comment]
@askudhay Looks like you have a simple typo, there is no slash between the pokemon module and the id.

Try:
`<a [routerLink]="['pokemon', i]">Pokemon&nbsp;{{ i }} </a>`

**Comment by askudhay** [comment]
HI @jlilly 

It didn't work.. Here is my code -  https://github.com/askudhay/pokemon-app/tree/preload-quicklink

Thanks!

**Comment by jlilly** [comment]
Hi @askudhay:

Good news, bad news time.

Good news: You are correct that the prefetch isn't working as promised
Bad news: It doesn't seem to do with the param `id` passed to the `routerLink`.

If you add the following line to your sidebar, you can see the pokemon-stats module load:
`<a *ngFor='let i of [1, 2, 3]' mat-list-item [routerLink]="['/pokemon', i]">Stats</a>`

**Comment by askudhay** [comment]
Thanks @jlilly! I can add the hyperlink in sidebar for Pokemon Stats, but I don't want it to be there. Anyway will see if @mgechev is giving some suggestion on this.. 

I am ready to fix that if that's really an issue.. BTW that will be my second OSS contribution, which is pretty much exciting.

Thanks!

**Comment by mgechev** [comment]
Doesn't look like an issue in quicklink. Make sure you add `QuicklinkModule` to your `PokemonModule`'s imports. Check out the text in bold in the ["Usage"](https://github.com/mgechev/ngx-quicklink#usage) section.
