### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by jlilly** [mgechev/ngx-quicklink#50]
There is a race condition that happens if the user navigates quickly between routes. It seems that the 
`IntersectionObserver` fires before the `LinkDirective` has a chance to register the link. When this happens, the `elementLink` map will return `undefined` and an error will be thrown.

**Comment by mgechev** [comment]
@jlilly with the current fix, ngx-quicklink would not prefetch the route since the observer would not trigger prefetching, right? If that's correct, shouldn't we delay the observer events for after the routerLink has been initialized?

**Comment by jlilly** [comment]
Correct, we bail if the element is not in the map, which is what was happening in this case. As far as I can tell, the `IntersectionObserver` for the observed link fires before the link gets removed from the `elementLink` map, but the its callback happens after the link has been removed from `elementLink` map. 

EG:

1. `IntersectionObserver` is created
1. The element is created by angular
2. `OnChanges` runs
    - This calls `LinkHandler.register()`
    - The link is both observed and added to  the `elementLink` map
    - Since the threshold is set to 0 (default) the `IntersectionObserver`'s callback is added to the event queue
4. The element is destroyed by angular
5. `OnDestroy` runs
    - This calls `LinkHandler.unregister()`
    - The link is both unobserved and removed from  the `elementLink` map
6. Finally the event queue catches up and the `IntersectionObserver` gets to run its callback
7. Throw error as element is no longer in the `elementLink` map

This happens in Firefox, but not Chrome. Haven't tested Opera, Safari, Edge or IE.

Another possible solution would be to set the threshold of the `IntersectionObserver` to 1.0 and only operate on fully visible links. I will mess with this today and see if that fixes the problem

**Comment by jlilly** [comment]
Changing the threshold does not work.

**Comment by mgechev** [comment]
Oh, I understand now. Originally I thought that the intersection observer fires before Angular registers the link (i.e. finds the directive). Yes, this fix makes sense. Merging and releasing as 0.2.3.
