### ISSUE TITLE
Typing conflict with ngneat/transloco

### ISSUE THREAD

**Issue by nartc** [mgechev/ngx-quicklink#52]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If a project uses `ngx-quicklink` together with `transloco-preload-langs-module`, there will be a typing conflict for `requestIdleCallback` and `cancelIdleCallback`. Project will fail to compile.
![image](https://user-images.githubusercontent.com/25516557/83208948-abb2cf00-a11c-11ea-9a95-4881cc1d1cc6.png)

## Expected behavior
Project should be able to compile.

Issue on `ngneat/transloco` https://github.com/ngneat/transloco/issues/291

**Comment by mgechev** [comment]
You can try 0.2.2. It doesn't declare any global typings.

**Comment by mgechev** [comment]
Here's the fix FYI https://github.com/mgechev/ngx-quicklink/commit/5a190d382fbfbbe01fd46f7d860ec390703f2c85

**Comment by nartc** [comment]
@mgechev Thanks for the quick fix. I didn't know which library to post the issue to so I posted to both. I was just using `patch-package` to patch `ngx-quicklink` to remove the type declaration.
