### ISSUE TITLE
Infinite CD loop in IE11 caused by IntersectionObserver polyfill

### ISSUE THREAD

**Issue by pshurygin** [mgechev/ngx-quicklink#61]
There is in issue when using ngx-quicklink (0.2.3) in IE11 alongside with some window positioning code (like positioning a dropdown), that relies on the zone.onStable observable.
The issue is caused by IntersectionObserver polyfill, which uses MutationObserver under the hood. This is the root issue in the angular repo with all the details and a reproducible scenario: https://github.com/angular/angular/issues/31712

The only workaround is to run IntersectionObserver callbacks outside of the angular zone, but that should be done on the ngx-quicklink side. I believe there is actually no need in running this callback inside the angular zone as it will not affect the UI in any way, so this should be an easy change.

**Comment by mgechev** [comment]
@pshurygin the change you propose sounds good to me. Would you want to open a PR?

**Comment by pshurygin** [comment]
@mgechev Sure!
