### ISSUE TITLE
Preloading child lazy-loaded modules inside the lazy-loaded module

### ISSUE THREAD

**Issue by EricPoul** [mgechev/ngx-quicklink#63]
## I'm submitting a...

```[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
```

## Current behavior
Lazy-loaded child modules inside the parent lazy-loaded module are preloaded together even if there is "routerLink" to only one of the child routes.

reproduction https://stackblitz.com/edit/angular-ivy-5ecbq2 (be aware that after moving to "home" click anywhere to update stackblitz console and see logs from loaded child modules)

## Expected behavior
A Lazy-loaded child module inside the parent lazy-loaded module are preloaded only if on a page is a "routerLink" with corresponding to this child module path.

**Comment by mgechev** [comment]
Do you have a reproduction at GitHub? StackBlitz doesn't seem to code-split as expected so it's hard to reproduce the problem there.

**Comment by EricPoul** [comment]
I changed a little your example from ngx-quicklink and reproduced it on https://ericpoul.github.io/ngx-quicklink-issue-reproduction (repo https://github.com/EricPoul/ngx-quicklink-issue-reproduction)

**Comment by mgechev** [comment]
I see, product was not supposed to be prefetched, right?

I'll not be able to get a bandwidth for this in the upcoming weeks. Will add `help wanted` label if someone can take it in the meantime.

**Comment by EricPoul** [comment]
Yes, you are right, product is supposed to be prefetched only if a page has a routerLink with a path to "product"
