### ISSUE TITLE
Routes are not getting lazy loaded inside empty path with children: []

### ISSUE THREAD

**Issue by visurel** [mgechev/ngx-quicklink#66]
Thanks a lot for this great library!
It looks like the preloading is not working in some specific cases. 

```typescript
const routes: Routes = [
  {
    path: '',
    component: LayoutComponent,
    children: [
      {
        path: 'home',
        loadChildren: () => import('./home/home.module').then(m => m.HomeModule)
      }
    ]
  }
];

```

When the routes are setup in this way, all routes inside the `children: []` are not preloaded.

I've debugged a bit with some console.logs and it seems like when the `{ path: 'home', loadChildren: ... }` is at the root, the path that the PreloadRegistry checks is `/home`, but when it's inside the `LayoutComponent children: []` it does a check on `//home` and returns a `shouldPrefetch: false` while when it's at the root it's `true`.

I've taken your example repo project and created a reproduction repo here: https://github.com/visurel/ngx-quicklink-bug

I hope it's understandable and somehow fixable (or am I doing something wrong here?)

**Comment by mgechev** [comment]
I had a chance to look into this today. It doesn't seem like a problem with Quicklink. You're missing imports of the `QuicklinkModule` in your `LayoutModule`. This way the directive which wraps your `routerLink`s is not available and there's no way for `ngx-quicklink` to hook into them with `IntersectionObserver`.
