### ISSUE TITLE
0.2.6 broken in IE11

### ISSUE THREAD

**Issue by Timebutt** [mgechev/ngx-quicklink#69]
I noticed the latest release `0.2.6` of `ngx-quicklink` no longer runs correctly in IE11 when upgrading it in my Angular app. The problem is that the published package no longer contains the `es5` and `fesm5` folders, a consequence of [upgrading](https://github.com/mgechev/ngx-quicklink/commit/69ad657851bbc5a9b42ef6672cc1c4e9f10c36ae) `@angular/compiler-cli` to `10.2.1` I'm guessing. 

There is code in this repository specifically for supporting older browsers, so I guess it's worth the effort to change the build to still build `es5` compatible artifacts? I wouldn't mind taking a stab at this, but wanted to open an issue for discussion first ;)

**Comment by mgechev** [comment]
Hey @Timebutt, sure, please do :)

**Comment by Timebutt** [comment]
It turns out my Angular project had an incorrect differential loading configuration which caused the issue. Having that sorted out, version `0.2.6` of `ngx-quicklink` works just fine in IE11 so the error was on my end 👍 

Closing!
