### ISSUE TITLE
Trigger preload from component

### ISSUE THREAD

**Issue by stoffason** [mgechev/ngx-quicklink#72]
Hi, nice solution!, Is there any way to trigger the preload of a route, programmatically directly from a component, rather than observing and triggering from the routerLink?

**Comment by stoffason** [comment]
no worries, found a solution...

`  controller ( 
        private router: Router
        private preload: RouterPreloader,
        private pre: ɵe
        ) {}
        
        ......

        this.pre.add(this._router.parseUrl('/whateverurl'))
        this.pre.shouldPrefetch('/whateverurl')
        this.preload.preload().subscribe(() => void 0);

        .......
        `

**Comment by mgechev** [comment]
👍 glad you found the workaround!
