### ISSUE TITLE
An accessor cannot be declared in an ambient contex - node_modules/ngx-quicklink/src/link.directive.d.ts(13,9)

### ISSUE THREAD

**Issue by dianmonblan** [mgechev/ngx-quicklink#75]
Hello, Failed to do **ng serve**

```
ERROR in node_modules/ngx-quicklink/src/link.directive.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ngx-quicklink/src/link.directive.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
```
_package.json_

```javascript
"@angular/cdk": "~8.0.1",
"@angular/common": "~8.0.1",
"@angular/compiler": "~8.0.1",
"@angular/core": "~8.0.1",
"ngx-quicklink": "^0.2.6",
...
"typescript": "~3.4.3",
```

Regards,

**Comment by rajat29gupta** [comment]
Any update on this issue

**Comment by dianmonblan** [comment]
> Any update on this issue?

Hello @rajat29gupta for me part I have had to update the project to angular 9, only solution finded for me. I hope it helps you.

[I recommend you use Angular Update Guide](https://update.angular.io/?v=8.2-9.1)

Regards,

**Comment by rajat29gupta** [comment]
Thanks, will try it out.

**Comment by mgechev** [comment]
Seems related to the TypeScript version. For compatibility with older Angular versions you can use previous versions of this package.
