### ISSUE TITLE
containsTree should be available as a util

### ISSUE THREAD

**Issue by mohammedzamakhan** [mgechev/ngx-quicklink#9]
I was creating a PrefetchStrategy, and I also needed similar function, that checks if two trees are similar.

Can this be a part of something like CDK or may @angular/router itself?

https://github.com/mgechev/ngx-quicklink/blob/98897f36a9e671d37a601c4568e1caea3fcae54b/src/prefetch-registry.service.ts#L34

**Comment by mohammedzamakhan** [comment]
and also findPath method
https://github.com/mgechev/ngx-quicklink/blob/98897f36a9e671d37a601c4568e1caea3fcae54b/src/quicklink-strategy.service.ts#L29

**Comment by mgechev** [comment]
Let's keep it separately for now. It's not worth it to extend the public API surface of the router.

**Comment by mohammedzamakhan** [comment]
I am copy pasting your code in my strategy https://github.com/mohammedzamakhan/ngx-perimeter/tree/master/projects/perimeter-strategy
